import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <nav className="h-[50px] flex items-center">
        <h1>Navbar</h1>
      </nav>
      <main className="flex flex-col justify-center items-center h-[calc(100%-50px)]">
        {children}
      </main>
    </body>
  </html>
);

export default RootLayout;
